# Configuration for the repo
REPO:
  NAME: servertools
  URL: https://github.com/barretobrock/${REPO_NAME}
  GIT_URL: git+${REPO_URL}.git#egg=${REPO_NAME}
  DIR: ${HOME}/extras/${REPO_NAME}
  VENV: ${HOME}/venvs/stools/bin/python
  DESC: A package for routines performed by my home automation server
  DEPS:
    - git+https://github.com/barretobrock/slacktools.git#egg=slacktools
    - git+https://github.com/barretobrock/kavalkilu.git#egg=kavalkilu
